name: Taro React Build

on:
  push:
    branches: [main, master]
    paths:
      - '**'
      - '!**/.github/workflows/**'
      - '.github/workflows/build.yaml'
  pull_request:
    branches: [main, master]
    paths:
      - '**'
      - '!**/.github/workflows/**'

jobs:
  test-and-lint:
    name: Test & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Lint Taro app
        run: yarn lint

      - name: Test Taro app
        run: yarn test

  build:
    name: Multi-platform Build
    runs-on: ubuntu-latest
    needs: test-and-lint
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build for H5
        run: yarn build:h5

      - name: Build for WeChat Mini Program
        run: yarn build:weapp

      - name: Upload H5 artifacts
        uses: actions/upload-artifact@v3
        with:
          name: h5-build
          path: dist-h5

      - name: Upload WeChat Mini Program artifacts
        uses: actions/upload-artifact@v3
        with:
          name: weapp-build
          path: dist-weapp
