name: Expo App Build

on:
  push:
    branches: [main, master]
    paths:
      - 'packages/demo-expo-app/**'
      - '.github/workflows/expo-app.yaml'
  pull_request:
    branches: [main, master]
    paths:
      - 'packages/demo-expo-app/**'

jobs:
  test-and-lint:
    name: Test & Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Lint Expo app
        run: yarn workspace demo-expo-app lint
        
      - name: Test Expo app
        run: yarn workspace demo-expo-app test:ci
  
  build:
    name: EAS Build
    runs-on: ubuntu-latest
    needs: test-and-lint
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Build on EAS
        run: cd packages/demo-expo-app && eas build --platform all --non-interactive 