name: React Vite Build

on:
  push:
    branches: [main, master]
    paths:
      - 'packages/demo-react-vite/**'
      - '.github/workflows/react-vite.yaml'
  pull_request:
    branches: [main, master]
    paths:
      - 'packages/demo-react-vite/**'

jobs:
  test-and-lint:
    name: Test & Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Lint React app
        run: yarn workspace demo-react-vite lint
        
      - name: Test React app
        run: yarn workspace demo-react-vite test
  
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: test-and-lint
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Build React app
        run: yarn workspace demo-react-vite build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: packages/demo-react-vite/dist
          
      # 如果需要部署到静态托管服务（例如 Netlify、Vercel 等），可以在这里添加部署步骤
      # 例如：
      # - name: Deploy to Netlify
      #   uses: nwtgck/actions-netlify@v2
      #   with:
      #     publish-dir: './packages/demo-react-vite/dist'
      #     production-branch: master
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     deploy-message: "Deploy from GitHub Actions"
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }} 